import React from 'react'
import { useState, useEffect } from 'react'

const DesktopGrid =()=>{

    return(
        <>
            <div className='container-fluid desktop-grid'>
                <div className='row'>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                    <div className='col'>test</div>
                </div>
            </div>
        </>
    )
}

export default DesktopGrid